MODEL:
  TYPE: mutual_learning
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 81
NUM_GPUS: 8
MEMONGER_SHARE_ACTIVATIONS: True
#PIXEL_MEANS: [0.485, 0.456, 0.406]
#PIXEL_DIV: 255.0
#PIXEL_STD: [0.229, 0.224, 0.225]
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  RPN_MAX_LEVEL: 7
  RPN_MIN_LEVEL: 3
  COARSEST_STRIDE: 128
  EXTRA_CONV_LEVELS: True
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 4
  ASPECT_RATIOS: (1.0, 2.0, 0.5)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 4
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
  #DECONV: True
  #DECONV_NUM: 4
RESNETS:
  CHANNEL_RATIO: 1.0
TRAIN:
  WEIGHTS: ../weights/R-50.pkl
  DATASETS: ('coco_2017_train',)
  SCALES: (400,)
  MAX_SIZE: 677
  RPN_STRADDLE_THRESH: -1  # default 0
  AUTO_RESUME: True
TEST:
  DATASETS: ('coco_2017_val',)
  SCALES: (400,)
  MAX_SIZE: 677
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 10000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000
OUTPUT_DIR: ./model/mutual_learning
DISTILLATION:
  DISTILLATION_ON: True
  LOSS_ALPHA: 0.5
  LOSS_GAMMA: 2.0
  WEIGHTS: 1.0
  HARD_WEIGHTS: 1.0
  FOCAL_TYPE: 0
  IGNORED_LABEL: -1
  TYPE: 'KD'
  ADAPTIVE_NORMALIZER: True
  LOGITS_POWER: 1.8
  TEMPERATURE: 1.0
  MUTUAL_LEARNING: True
  UNLABEL_DISTILLATION: False
  USE_GT_BBOX: True
  UNLABEL_DATASETS: ('coco_2017_train','coco_2017_unlabel')
  CONF_THRESH: 1.0
  #DEBUG: True
  