#DEBUG: True
MODEL:
  TYPE: retinanet
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 81
NUM_GPUS: 8
#PIXEL_MEANS: [0.485, 0.456, 0.406]
#PIXEL_DIV: 255.0
#PIXEL_STD: [0.229, 0.224, 0.225]
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 90000
  STEPS: [0, 60000, 80000]
  #WARM_UP_ITERS: 1000
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  RPN_MAX_LEVEL: 7
  RPN_MIN_LEVEL: 3
  COARSEST_STRIDE: 128
  EXTRA_CONV_LEVELS: True
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 4
  ASPECT_RATIOS: (1.0, 2.0, 0.5)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 4
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
  #ONE_HOT_TARGET: True
RESNETS:
  CHANNEL_RATIO: 1.0
TRAIN:
  WEIGHTS: ./model/R50_600/train/coco_2017_train/retinanet/model_final.pkl
  DATASETS: ('coco_2017_train',)
  SCALES: (500,)
  MAX_SIZE: 833
  RPN_STRADDLE_THRESH: -1  # default 0
  AUTO_RESUME: False
TEST:
  DATASETS: ('coco_2017_unlabel',)
  WEIGHTS: ./model/R50_500/train/coco_2017_train/retinanet/model_final.pkl
  SCALES: (500,)
  MAX_SIZE: 833
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 10000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000
OUTPUT_DIR: ./model/R50_500
