MODEL:
  TYPE: retinanet
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 81
  #EXECUTION_TYPE: prof_dag
NUM_GPUS: 8
MEMONGER_SHARE_ACTIVATIONS: True
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 270000
  STEPS: [0, 180000,240000]
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  RPN_MAX_LEVEL: 7
  RPN_MIN_LEVEL: 3
  COARSEST_STRIDE: 128
  EXTRA_CONV_LEVELS: True
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 4
  ASPECT_RATIOS: (1.0, 2.0, 0.5)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 4
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
  DECONV: True
  DECONV_NUM: 4
  DECONV_TYPE: 0
  FINAL_KERNEL_SIZE: 3
  #PRIOR_PROB: 0.04
TRAIN:
  WEIGHTS: ../weights/R-50.pkl
  DATASETS: ('coco_2017_train','coco_2017_unlabel')
  SCALES: (400,)
  MAX_SIZE: 677
  RPN_STRADDLE_THRESH: -1  # default 0
  AUTO_RESUME: True
  #IMS_PER_BATCH: 1
TEST:
  DATASETS: ('coco_2017_val',)
  SCALES: (400,)
  MAX_SIZE: 677
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 10000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000
OUTPUT_DIR: ./model/deconv_unlabel_270k
DISTILLATION:
  HARD_WEIGHTS: 1.0
  ADD_ONE_FG_NUM: 1.0
#  DISTILLATION_ON: True
#  LOSS_ALPHA: 0.75
#  LOSS_GAMMA: 0
  